# Initialize the cluster and install Flanner (for provider of pod network plugin)
---
- hosts: masters
  become: yes
  tasks:
  # This task not realy working
  - name: install  ACL
    apt:
      name: acl
      state: present
  
  - name: initialize the cluster
    become: yes
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.7.149 >> cluster_initialized.txt
    args:
      chdir: /home/iotadmin
      creates: cluster_initialized.txt 
  
  - name: create .kube directory
    become: yes
    file:
      path: /home/iotadmin/.kube
      state: directory
      mode: 0755
  
  - name: copy admin.conf to user's kube config
    become: yes
    copy: 
      src: /etc/kubernetes/admin.conf
      dest: /home/iotadmin/.kube/config
      remote_src: yes
      owner: iotadmin

  - name: install Pod network
    become_user: iotadmin
    become: yes
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
