# Adding workers to the cluster
---
- hosts: masters
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: reset kubeadm
      shell: kubeadm reset -f kubeadm init

    - name: join cluster
      shell: "{{ hostvars['master'].join_command }}  >> node_joined.txt"
      args:
        chdir: /home/iotadmin
        creates: node_joined.txt
