---
- hosts: nfs-clients
  become: yes
  tasks:
    - name: install nfs-utils
      apt: name=nfs-common state=latest

    - name: Create a mountable directory if it does not exist
      file:
        path: /mnt/data
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0775'
    - name: Mount volumn
      shell: sudo mount 10.2.20.207:/home/vagrant/data /mnt/data